#############################################################################
# Makefile for building: sunshine
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sat Jun 4 15:34:34 2011
# Project:  sunshine.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile sunshine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lGLEW -lQtWebKit -lQtScript -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sunshine.cpp \
		panelgl.cpp \
		shader.cpp \
		camera.cpp \
		util.cpp \
		geometry.cpp \
		register.cpp \
		primitive.cpp moc_sunshine.cpp
OBJECTS       = main.o \
		sunshine.o \
		panelgl.o \
		shader.o \
		camera.o \
		util.o \
		geometry.o \
		register.o \
		primitive.o \
		moc_sunshine.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sunshine.pro
QMAKE_TARGET  = sunshine
DESTDIR       = 
TARGET        = sunshine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_sunshine.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sunshine.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtScript.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile sunshine.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtScript.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile sunshine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sunshine1.0.0 || $(MKDIR) .tmp/sunshine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents sunshine.h panelgl.h shader.h util.h camera.h geometry.h register.h primitive.h .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents main.cpp sunshine.cpp panelgl.cpp shader.cpp camera.cpp util.cpp geometry.cpp register.cpp primitive.cpp .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents sunshine.ui .tmp/sunshine1.0.0/ && (cd `dirname .tmp/sunshine1.0.0` && $(TAR) sunshine1.0.0.tar sunshine1.0.0 && $(COMPRESS) sunshine1.0.0.tar) && $(MOVE) `dirname .tmp/sunshine1.0.0`/sunshine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sunshine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sunshine.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sunshine.cpp
moc_sunshine.cpp: sunshine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sunshine.h -o moc_sunshine.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_sunshine.h
compiler_uic_clean:
	-$(DEL_FILE) ui_sunshine.h
ui_sunshine.h: sunshine.ui \
		panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h
	/usr/bin/uic-qt4 sunshine.ui -o ui_sunshine.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp sunshine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sunshine.o: sunshine.cpp sunshine.h \
		ui_sunshine.h \
		panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunshine.o sunshine.cpp

panelgl.o: panelgl.cpp panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panelgl.o panelgl.cpp

shader.o: shader.cpp shader.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shader.o shader.cpp

camera.o: camera.cpp camera.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

geometry.o: geometry.cpp geometry.h \
		primitive.h \
		util.h \
		register.h \
		camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o geometry.cpp

register.o: register.cpp register.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

primitive.o: primitive.cpp primitive.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o primitive.o primitive.cpp

moc_sunshine.o: moc_sunshine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sunshine.o moc_sunshine.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

