#############################################################################
# Makefile for building: sunshine
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue Nov 1 21:21:24 2011
# Project:  sunshine.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sunshine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -I/usr/include/python2.7 -I/usr/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-32 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtScript -I/usr/include/qt4 -I. -Isrc -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -ldl -lutil -lm -lpython2.7 -lGLEW -laqsis_core -lboost_python -lQtScript -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/camera.cpp \
		src/face_util.cpp \
		src/geometry.cpp \
		src/imageviewer.cpp \
		src/panelgl.cpp \
		src/primitive.cpp \
		src/project_util.cpp \
		src/scene.cpp \
		src/select.cpp \
		src/settings.cpp \
		src/shader.cpp \
		src/sunshine.cpp \
		src/util.cpp \
		src/vertex_util.cpp \
		src/sunshineui.cpp \
		src/main.cpp \
		src/attribute_editor.cpp \
		src/renderwidget.cpp \
		src/exceptions.cpp \
		src/python_bindings.cpp \
		src/object_tools.cpp \
		src/contextmenu.cpp \
		src/cursor_tools.cpp \
		src/draw_box_tool.cpp \
		src/render_util.cpp \
		src/material.cpp \
		src/light.cpp \
		src/transformable.cpp \
		src/bindable.cpp moc_imageviewer.cpp \
		moc_panelgl.cpp \
		moc_sunshine.cpp \
		moc_attribute_editor.cpp \
		moc_renderwidget.cpp \
		moc_contextmenu.cpp \
		moc_cursor_tools.cpp \
		moc_transformable.cpp \
		moc_bindable.cpp \
		qrc_plugins.cpp \
		qrc_icons.cpp \
		qrc_textures.cpp
OBJECTS       = camera.o \
		face_util.o \
		geometry.o \
		imageviewer.o \
		panelgl.o \
		primitive.o \
		project_util.o \
		scene.o \
		select.o \
		settings.o \
		shader.o \
		sunshine.o \
		util.o \
		vertex_util.o \
		sunshineui.o \
		main.o \
		attribute_editor.o \
		renderwidget.o \
		exceptions.o \
		python_bindings.o \
		object_tools.o \
		contextmenu.o \
		cursor_tools.o \
		draw_box_tool.o \
		render_util.o \
		material.o \
		light.o \
		transformable.o \
		bindable.o \
		moc_imageviewer.o \
		moc_panelgl.o \
		moc_sunshine.o \
		moc_attribute_editor.o \
		moc_renderwidget.o \
		moc_contextmenu.o \
		moc_cursor_tools.o \
		moc_transformable.o \
		moc_bindable.o \
		qrc_plugins.o \
		qrc_icons.o \
		qrc_textures.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sunshine.pro
QMAKE_TARGET  = sunshine
DESTDIR       = 
TARGET        = sunshine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_sunshine.h ui_renderwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sunshine.pro  /usr/share/qt4/mkspecs/linux-g++-32/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtScript.prl \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sunshine.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtScript.prl:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sunshine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sunshine1.0.0 || $(MKDIR) .tmp/sunshine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents src/camera.h src/face_util.h src/geometry.h src/imageviewer.h src/panelgl.h src/primitive.h src/project_util.h src/scene.h src/select.h src/settings.h src/shader.h src/sunshine.h src/util.h src/vertex_util.h src/sunshineui.h src/sunshine.h src/attribute_editor.h src/renderwidget.h src/exceptions.h src/python_bindings.h src/object_tools.h src/worktool.h src/contextmenu.h src/cursor_tools.h src/render_util.h src/material.h src/light.h src/transformable.h src/bindable.h .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents src/plugins.qrc src/icons.qrc src/textures.qrc .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents src/camera.cpp src/face_util.cpp src/geometry.cpp src/imageviewer.cpp src/panelgl.cpp src/primitive.cpp src/project_util.cpp src/scene.cpp src/select.cpp src/settings.cpp src/shader.cpp src/sunshine.cpp src/util.cpp src/vertex_util.cpp src/sunshineui.cpp src/main.cpp src/attribute_editor.cpp src/renderwidget.cpp src/exceptions.cpp src/python_bindings.cpp src/object_tools.cpp src/contextmenu.cpp src/cursor_tools.cpp src/draw_box_tool.cpp src/render_util.cpp src/material.cpp src/light.cpp src/transformable.cpp src/bindable.cpp .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents src/sunshine.ui src/renderwidget.ui .tmp/sunshine1.0.0/ && (cd `dirname .tmp/sunshine1.0.0` && $(TAR) sunshine1.0.0.tar sunshine1.0.0 && $(COMPRESS) sunshine1.0.0.tar) && $(MOVE) `dirname .tmp/sunshine1.0.0`/sunshine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sunshine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_imageviewer.cpp moc_panelgl.cpp moc_sunshine.cpp moc_sunshine.cpp moc_attribute_editor.cpp moc_renderwidget.cpp moc_contextmenu.cpp moc_cursor_tools.cpp moc_transformable.cpp moc_bindable.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_imageviewer.cpp moc_panelgl.cpp moc_sunshine.cpp moc_sunshine.cpp moc_attribute_editor.cpp moc_renderwidget.cpp moc_contextmenu.cpp moc_cursor_tools.cpp moc_transformable.cpp moc_bindable.cpp
moc_imageviewer.cpp: src/imageviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/imageviewer.h -o moc_imageviewer.cpp

moc_panelgl.cpp: src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/panelgl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/panelgl.h -o moc_panelgl.cpp

moc_sunshine.cpp: src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/sunshine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/sunshine.h -o moc_sunshine.cpp

moc_sunshine.cpp: src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/sunshine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/sunshine.h -o moc_sunshine.cpp

moc_attribute_editor.cpp: src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/attribute_editor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/attribute_editor.h -o moc_attribute_editor.cpp

moc_renderwidget.cpp: src/imageviewer.h \
		src/renderwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/renderwidget.h -o moc_renderwidget.cpp

moc_contextmenu.cpp: src/worktool.h \
		src/contextmenu.h \
		src/util.h \
		src/exceptions.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/contextmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/contextmenu.h -o moc_contextmenu.cpp

moc_cursor_tools.cpp: src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/select.h \
		src/cursor_tools.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/cursor_tools.h -o moc_cursor_tools.cpp

moc_transformable.cpp: src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/transformable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/transformable.h -o moc_transformable.cpp

moc_bindable.cpp: src/exceptions.h \
		src/bindable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/bindable.h -o moc_bindable.cpp

compiler_rcc_make_all: qrc_plugins.cpp qrc_icons.cpp qrc_textures.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_plugins.cpp qrc_icons.cpp qrc_textures.cpp
qrc_plugins.cpp: src/plugins.qrc \
		src/objImporter.py \
		src/meshImporter.py
	/usr/bin/rcc -name plugins src/plugins.qrc -o qrc_plugins.cpp

qrc_icons.cpp: src/icons.qrc \
		src/point_light_icon.png \
		src/draw_box_tool.png \
		src/extrude_tool.png \
		src/translate_tool.png \
		src/edit_tool.png \
		src/point_tool.png \
		src/object_work_mode.png \
		src/rotate_tool.png \
		src/material_icon.png \
		src/camera_icon.png \
		src/mesh_icon.png
	/usr/bin/rcc -name icons src/icons.qrc -o qrc_icons.cpp

qrc_textures.cpp: src/textures.qrc \
		src/checker_texture_soft.png \
		src/checker_texture.png
	/usr/bin/rcc -name textures src/textures.qrc -o qrc_textures.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_sunshine.h ui_renderwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_sunshine.h ui_renderwidget.h
ui_sunshine.h: src/sunshine.ui
	/usr/bin/uic-qt4 src/sunshine.ui -o ui_sunshine.h

ui_renderwidget.h: src/renderwidget.ui
	/usr/bin/uic-qt4 src/renderwidget.ui -o ui_renderwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

camera.o: src/camera.cpp src/camera.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o src/camera.cpp

face_util.o: src/face_util.cpp src/face_util.h \
		src/geometry.h \
		src/primitive.h \
		src/util.h \
		src/exceptions.h \
		src/material.h \
		src/attribute_editor.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o face_util.o src/face_util.cpp

geometry.o: src/geometry.cpp src/geometry.h \
		src/primitive.h \
		src/util.h \
		src/exceptions.h \
		src/material.h \
		src/attribute_editor.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o src/geometry.cpp

imageviewer.o: src/imageviewer.cpp src/imageviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewer.o src/imageviewer.cpp

panelgl.o: src/panelgl.cpp src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/select.h \
		src/project_util.h \
		src/face_util.h \
		src/vertex_util.h \
		src/cursor_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panelgl.o src/panelgl.cpp

primitive.o: src/primitive.cpp src/primitive.h \
		src/util.h \
		src/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o primitive.o src/primitive.cpp

project_util.o: src/project_util.cpp src/project_util.h \
		src/geometry.h \
		src/primitive.h \
		src/util.h \
		src/exceptions.h \
		src/material.h \
		src/attribute_editor.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project_util.o src/project_util.cpp

scene.o: src/scene.cpp src/scene.h \
		src/util.h \
		src/exceptions.h \
		src/camera.h \
		src/transformable.h \
		src/bindable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/attribute_editor.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/python_bindings.h \
		src/object_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o src/scene.cpp

select.o: src/select.cpp src/select.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/face_util.h \
		src/vertex_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o select.o src/select.cpp

settings.o: src/settings.cpp src/settings.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o src/settings.cpp

shader.o: src/shader.cpp src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shader.o src/shader.cpp

sunshine.o: src/sunshine.cpp src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		ui_sunshine.h \
		src/sunshineui.h \
		src/object_tools.h \
		src/cursor_tools.h \
		src/select.h \
		src/render_util.h \
		src/modeltest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunshine.o src/sunshine.cpp

util.o: src/util.cpp src/util.h \
		src/exceptions.h \
		src/light.h \
		src/transformable.h \
		src/bindable.h \
		src/attribute_editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o src/util.cpp

vertex_util.o: src/vertex_util.cpp src/vertex_util.h \
		src/geometry.h \
		src/primitive.h \
		src/util.h \
		src/exceptions.h \
		src/material.h \
		src/attribute_editor.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/face_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vertex_util.o src/vertex_util.cpp

sunshineui.o: src/sunshineui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunshineui.o src/sunshineui.cpp

main.o: src/main.cpp src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

attribute_editor.o: src/attribute_editor.cpp src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/material.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attribute_editor.o src/attribute_editor.cpp

renderwidget.o: src/renderwidget.cpp src/renderwidget.h \
		src/imageviewer.h \
		ui_renderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderwidget.o src/renderwidget.cpp

exceptions.o: src/exceptions.cpp src/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exceptions.o src/exceptions.cpp

python_bindings.o: src/python_bindings.cpp src/python_bindings.h \
		src/exceptions.h \
		src/primitive.h \
		src/util.h \
		src/geometry.h \
		src/material.h \
		src/attribute_editor.h \
		src/bindable.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o python_bindings.o src/python_bindings.cpp

object_tools.o: src/object_tools.cpp src/object_tools.h \
		src/worktool.h \
		src/contextmenu.h \
		src/util.h \
		src/exceptions.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object_tools.o src/object_tools.cpp

contextmenu.o: src/contextmenu.cpp src/contextmenu.h \
		src/worktool.h \
		src/util.h \
		src/exceptions.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contextmenu.o src/contextmenu.cpp

cursor_tools.o: src/cursor_tools.cpp src/cursor_tools.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/select.h \
		src/face_util.h \
		src/vertex_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cursor_tools.o src/cursor_tools.cpp

draw_box_tool.o: src/draw_box_tool.cpp src/cursor_tools.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw_box_tool.o src/draw_box_tool.cpp

render_util.o: src/render_util.cpp src/render_util.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h \
		src/material.h \
		src/camera.h \
		src/geometry.h \
		src/primitive.h \
		src/scene.h \
		src/worktool.h \
		src/contextmenu.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o render_util.o src/render_util.cpp

material.o: src/material.cpp src/material.h \
		src/attribute_editor.h \
		src/exceptions.h \
		src/util.h \
		src/bindable.h \
		src/sunshine.h \
		src/renderwidget.h \
		src/imageviewer.h \
		src/settings.h \
		src/scene.h \
		src/camera.h \
		src/transformable.h \
		src/geometry.h \
		src/primitive.h \
		src/worktool.h \
		src/contextmenu.h \
		src/panelgl.h \
		src/shader.h \
		src/light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o material.o src/material.cpp

light.o: src/light.cpp src/light.h \
		src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h \
		src/attribute_editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o src/light.cpp

transformable.o: src/transformable.cpp src/transformable.h \
		src/util.h \
		src/exceptions.h \
		src/bindable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transformable.o src/transformable.cpp

bindable.o: src/bindable.cpp src/bindable.h \
		src/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bindable.o src/bindable.cpp

moc_imageviewer.o: moc_imageviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageviewer.o moc_imageviewer.cpp

moc_panelgl.o: moc_panelgl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panelgl.o moc_panelgl.cpp

moc_sunshine.o: moc_sunshine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sunshine.o moc_sunshine.cpp

moc_attribute_editor.o: moc_attribute_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attribute_editor.o moc_attribute_editor.cpp

moc_renderwidget.o: moc_renderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderwidget.o moc_renderwidget.cpp

moc_contextmenu.o: moc_contextmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contextmenu.o moc_contextmenu.cpp

moc_cursor_tools.o: moc_cursor_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cursor_tools.o moc_cursor_tools.cpp

moc_transformable.o: moc_transformable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transformable.o moc_transformable.cpp

moc_bindable.o: moc_bindable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bindable.o moc_bindable.cpp

qrc_plugins.o: qrc_plugins.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_plugins.o qrc_plugins.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_textures.o: qrc_textures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textures.o qrc_textures.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

