#############################################################################
# Makefile for building: sunshine
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sun Jun 26 15:01:43 2011
# Project:  sunshine.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile sunshine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lGLEW -laqsis_core -lQtWebKit -lQtScript -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sunshine.cpp \
		panelgl.cpp \
		shader.cpp \
		camera.cpp \
		util.cpp \
		geometry.cpp \
		register.cpp \
		primitive.cpp \
		renderwidget.cpp \
		imageviewer.cpp \
		settings.cpp \
		qtpropertybrowser/qtbuttonpropertybrowser.cpp \
		qtpropertybrowser/qteditorfactory.cpp \
		qtpropertybrowser/qtgroupboxpropertybrowser.cpp \
		qtpropertybrowser/qtpropertybrowser.cpp \
		qtpropertybrowser/qtpropertybrowserutils.cpp \
		qtpropertybrowser/qtpropertymanager.cpp \
		qtpropertybrowser/qttreepropertybrowser.cpp \
		qtpropertybrowser/qtvariantproperty.cpp \
		select.cpp \
		face_util.cpp \
		project_util.cpp \
		vertex_util.cpp moc_sunshine.cpp \
		moc_renderwidget.cpp \
		moc_imageviewer.cpp \
		moc_qtpropertybrowserutils_p.cpp
OBJECTS       = main.o \
		sunshine.o \
		panelgl.o \
		shader.o \
		camera.o \
		util.o \
		geometry.o \
		register.o \
		primitive.o \
		renderwidget.o \
		imageviewer.o \
		settings.o \
		qtbuttonpropertybrowser.o \
		qteditorfactory.o \
		qtgroupboxpropertybrowser.o \
		qtpropertybrowser.o \
		qtpropertybrowserutils.o \
		qtpropertymanager.o \
		qttreepropertybrowser.o \
		qtvariantproperty.o \
		select.o \
		face_util.o \
		project_util.o \
		vertex_util.o \
		moc_sunshine.o \
		moc_renderwidget.o \
		moc_imageviewer.o \
		moc_qtpropertybrowserutils_p.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sunshine.pro
QMAKE_TARGET  = sunshine
DESTDIR       = 
TARGET        = sunshine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_sunshine.h ui_renderwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sunshine.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtScript.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile sunshine.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtScript.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile sunshine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sunshine1.0.0 || $(MKDIR) .tmp/sunshine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents sunshine.h panelgl.h shader.h util.h camera.h geometry.h register.h primitive.h renderwidget.h imageviewer.h settings.h qtpropertybrowser/qtbuttonpropertybrowser.h qtpropertybrowser/qteditorfactory.h qtpropertybrowser/qtgroupboxpropertybrowser.h qtpropertybrowser/qtpropertybrowser.h qtpropertybrowser/qtpropertybrowserutils_p.h qtpropertybrowser/qtpropertymanager.h qtpropertybrowser/qttreepropertybrowser.h qtpropertybrowser/qtvariantproperty.h select.h face_util.h project_util.h vertex_util.h .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents main.cpp sunshine.cpp panelgl.cpp shader.cpp camera.cpp util.cpp geometry.cpp register.cpp primitive.cpp renderwidget.cpp imageviewer.cpp settings.cpp qtpropertybrowser/qtbuttonpropertybrowser.cpp qtpropertybrowser/qteditorfactory.cpp qtpropertybrowser/qtgroupboxpropertybrowser.cpp qtpropertybrowser/qtpropertybrowser.cpp qtpropertybrowser/qtpropertybrowserutils.cpp qtpropertybrowser/qtpropertymanager.cpp qtpropertybrowser/qttreepropertybrowser.cpp qtpropertybrowser/qtvariantproperty.cpp select.cpp face_util.cpp project_util.cpp vertex_util.cpp .tmp/sunshine1.0.0/ && $(COPY_FILE) --parents sunshine.ui renderwidget.ui .tmp/sunshine1.0.0/ && (cd `dirname .tmp/sunshine1.0.0` && $(TAR) sunshine1.0.0.tar sunshine1.0.0 && $(COMPRESS) sunshine1.0.0.tar) && $(MOVE) `dirname .tmp/sunshine1.0.0`/sunshine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sunshine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sunshine.cpp moc_renderwidget.cpp moc_imageviewer.cpp moc_qtbuttonpropertybrowser.cpp moc_qteditorfactory.cpp moc_qtgroupboxpropertybrowser.cpp moc_qtpropertybrowser.cpp moc_qtpropertybrowserutils_p.cpp moc_qtpropertymanager.cpp moc_qttreepropertybrowser.cpp moc_qtvariantproperty.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sunshine.cpp moc_renderwidget.cpp moc_imageviewer.cpp moc_qtbuttonpropertybrowser.cpp moc_qteditorfactory.cpp moc_qtgroupboxpropertybrowser.cpp moc_qtpropertybrowser.cpp moc_qtpropertybrowserutils_p.cpp moc_qtpropertymanager.cpp moc_qttreepropertybrowser.cpp moc_qtvariantproperty.cpp
moc_sunshine.cpp: renderwidget.h \
		imageviewer.h \
		settings.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		sunshine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sunshine.h -o moc_sunshine.cpp

moc_renderwidget.cpp: imageviewer.h \
		renderwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) renderwidget.h -o moc_renderwidget.cpp

moc_imageviewer.cpp: imageviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imageviewer.h -o moc_imageviewer.cpp

moc_qtbuttonpropertybrowser.cpp: qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtbuttonpropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtbuttonpropertybrowser.h -o moc_qtbuttonpropertybrowser.cpp

moc_qteditorfactory.cpp: qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qteditorfactory.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qteditorfactory.h -o moc_qteditorfactory.cpp

moc_qtgroupboxpropertybrowser.cpp: qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtgroupboxpropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtgroupboxpropertybrowser.h -o moc_qtgroupboxpropertybrowser.cpp

moc_qtpropertybrowser.cpp: qtpropertybrowser/qtpropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtpropertybrowser.h -o moc_qtpropertybrowser.cpp

moc_qtpropertybrowserutils_p.cpp: qtpropertybrowser/qtpropertybrowserutils_p.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtpropertybrowserutils_p.h -o moc_qtpropertybrowserutils_p.cpp

moc_qtpropertymanager.cpp: qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertymanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtpropertymanager.h -o moc_qtpropertymanager.cpp

moc_qttreepropertybrowser.cpp: qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qttreepropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qttreepropertybrowser.h -o moc_qttreepropertybrowser.cpp

moc_qtvariantproperty.cpp: qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtvariantproperty.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtvariantproperty.h -o moc_qtvariantproperty.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: qteditorfactory.moc qtpropertymanager.moc qttreepropertybrowser.moc
compiler_moc_source_clean:
	-$(DEL_FILE) qteditorfactory.moc qtpropertymanager.moc qttreepropertybrowser.moc
qteditorfactory.moc: qtpropertybrowser/qteditorfactory.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowserutils_p.h \
		moc_qteditorfactory.cpp \
		qtpropertybrowser/qteditorfactory.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qteditorfactory.cpp -o qteditorfactory.moc

qtpropertymanager.moc: qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowserutils_p.h \
		moc_qtpropertymanager.cpp \
		qtpropertybrowser/qtpropertymanager.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qtpropertymanager.cpp -o qtpropertymanager.moc

qttreepropertybrowser.moc: qtpropertybrowser/qttreepropertybrowser.h \
		qtpropertybrowser/qtpropertybrowser.h \
		moc_qttreepropertybrowser.cpp \
		qtpropertybrowser/qttreepropertybrowser.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtpropertybrowser/qttreepropertybrowser.cpp -o qttreepropertybrowser.moc

compiler_uic_make_all: ui_sunshine.h ui_renderwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_sunshine.h ui_renderwidget.h
ui_sunshine.h: sunshine.ui \
		panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h
	/usr/bin/uic-qt4 sunshine.ui -o ui_sunshine.h

ui_renderwidget.h: renderwidget.ui
	/usr/bin/uic-qt4 renderwidget.ui -o ui_renderwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: main.cpp sunshine.h \
		renderwidget.h \
		imageviewer.h \
		settings.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sunshine.o: sunshine.cpp sunshine.h \
		renderwidget.h \
		imageviewer.h \
		settings.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		ui_sunshine.h \
		register.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunshine.o sunshine.cpp

panelgl.o: panelgl.cpp panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h \
		select.h \
		project_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panelgl.o panelgl.cpp

shader.o: shader.cpp shader.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shader.o shader.cpp

camera.o: camera.cpp camera.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

geometry.o: geometry.cpp geometry.h \
		primitive.h \
		util.h \
		register.h \
		camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o geometry.cpp

register.o: register.cpp register.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

primitive.o: primitive.cpp primitive.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o primitive.o primitive.cpp

renderwidget.o: renderwidget.cpp renderwidget.h \
		imageviewer.h \
		ui_renderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderwidget.o renderwidget.cpp

imageviewer.o: imageviewer.cpp imageviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewer.o imageviewer.cpp

settings.o: settings.cpp settings.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/QtAbstractPropertyManager \
		qtpropertybrowser/QtIntPropertyManager \
		qtpropertybrowser/qtvariantproperty.h \
		qtpropertybrowser/qttreepropertybrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

qtbuttonpropertybrowser.o: qtpropertybrowser/qtbuttonpropertybrowser.cpp qtpropertybrowser/qtbuttonpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowser.h \
		moc_qtbuttonpropertybrowser.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtbuttonpropertybrowser.o qtpropertybrowser/qtbuttonpropertybrowser.cpp

qteditorfactory.o: qtpropertybrowser/qteditorfactory.cpp qtpropertybrowser/qteditorfactory.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowserutils_p.h \
		moc_qteditorfactory.cpp \
		qteditorfactory.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qteditorfactory.o qtpropertybrowser/qteditorfactory.cpp

qtgroupboxpropertybrowser.o: qtpropertybrowser/qtgroupboxpropertybrowser.cpp qtpropertybrowser/qtgroupboxpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowser.h \
		moc_qtgroupboxpropertybrowser.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtgroupboxpropertybrowser.o qtpropertybrowser/qtgroupboxpropertybrowser.cpp

qtpropertybrowser.o: qtpropertybrowser/qtpropertybrowser.cpp qtpropertybrowser/qtpropertybrowser.h \
		moc_qtpropertybrowser.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertybrowser.o qtpropertybrowser/qtpropertybrowser.cpp

qtpropertybrowserutils.o: qtpropertybrowser/qtpropertybrowserutils.cpp qtpropertybrowser/qtpropertybrowserutils_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertybrowserutils.o qtpropertybrowser/qtpropertybrowserutils.cpp

qtpropertymanager.o: qtpropertybrowser/qtpropertymanager.cpp qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertybrowserutils_p.h \
		moc_qtpropertymanager.cpp \
		qtpropertymanager.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertymanager.o qtpropertybrowser/qtpropertymanager.cpp

qttreepropertybrowser.o: qtpropertybrowser/qttreepropertybrowser.cpp qtpropertybrowser/qttreepropertybrowser.h \
		qtpropertybrowser/qtpropertybrowser.h \
		moc_qttreepropertybrowser.cpp \
		qttreepropertybrowser.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qttreepropertybrowser.o qtpropertybrowser/qttreepropertybrowser.cpp

qtvariantproperty.o: qtpropertybrowser/qtvariantproperty.cpp qtpropertybrowser/qtvariantproperty.h \
		qtpropertybrowser/qtpropertybrowser.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qteditorfactory.h \
		moc_qtvariantproperty.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtvariantproperty.o qtpropertybrowser/qtvariantproperty.cpp

select.o: select.cpp select.h \
		panelgl.h \
		shader.h \
		util.h \
		camera.h \
		geometry.h \
		primitive.h \
		register.h \
		face_util.h \
		vertex_util.h \
		sunshine.h \
		renderwidget.h \
		imageviewer.h \
		settings.h \
		qtpropertybrowser/qtpropertymanager.h \
		qtpropertybrowser/qtpropertybrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o select.o select.cpp

face_util.o: face_util.cpp face_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o face_util.o face_util.cpp

project_util.o: project_util.cpp project_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project_util.o project_util.cpp

vertex_util.o: vertex_util.cpp vertex_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vertex_util.o vertex_util.cpp

moc_sunshine.o: moc_sunshine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sunshine.o moc_sunshine.cpp

moc_renderwidget.o: moc_renderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderwidget.o moc_renderwidget.cpp

moc_imageviewer.o: moc_imageviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageviewer.o moc_imageviewer.cpp

moc_qtpropertybrowserutils_p.o: moc_qtpropertybrowserutils_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtpropertybrowserutils_p.o moc_qtpropertybrowserutils_p.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

